server:
  # 连接端口
  port: 8081
malody:
  server:
    api: 202310
    min: 202310
    # 欢迎词
    welcome: Welcome to this osu! to MalodyV server
    # 缓存路径，推荐设置绝对路径
    tmp: "/tmp/Osu2Malody"
  osu:
    clientID: 
    clientSecret: